name: Fetch and Update Web Content

on:
  schedule:
  - cron: "2 23 * * *"  # 北京时间 7:02
  - cron: "2 4 * * *"   # 北京时间 12:02
  - cron: "2 11 * * *"  # 北京时间 19:02
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码仓库
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    # Step 3: 安装依赖
    - name: Install dependencies
      run: pip install requests PyGithub

    # Step 4: 运行 Python 脚本
    - name: Run script
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        REPO_NAME: ${{ vars.REPO_NAME }}
        FILE_PATH: ${{ vars.FILE_PATH }}
        WEBPAGE_URL: ${{ vars.WEBPAGE_URL }}
      
      run: python script.py
